
class Uloge:
    kupac = "kupac"
    prodavac = "prodavac"
    menadzer = "menadzer"
    sve_uloge = ["kupac", "prodavac", "menadzer"]

class Zanrovi:
    avantura = "avantura"
    animacija = "animacija"
    akcija = "akcija"
    biografski = "biografski"
    vestern = "vestern"
    decji = "decji"
    dokumentarni = "dokumentarni"
    drama = "drama"
    istorijski = "istorijski"
    komedija = "komedija"
    kriminalisticki = "kriminalisticki"
    ljubavni = "ljubavni"
    misterija = "misterija"
    mjuzikl = "mjuzikl"
    naucnofantasticni = "naucnofantasticni"
    porodicni = "porodicni"
    ratni = "ratni"
    triler = "triler"
    fantastika = "fantastika"
    horor = "horor"
    svi_zanrovi = [
        "avantura"
        "animacija"
        "akcija"
        "biografski"
        "vestern"
        "decji"
        "dokumentarni"
        "drama"
        "istorijski"
        "komedija"
        "kriminalisticki"
        "ljubavni"
        "misterija"
        "mjuzikl"
        "naucnofantasticni"
        "porodicni"
        "ratni"
        "triler"
        "fantastika"
        "horor"
    ]

class Dani:
    ponedeljak = "ponedeljak"
    utorak = "utorak"
    sreda = "sreda"
    cetvrtak = "cetvrtak"
    petak = "petak"
    subota = "subota"
    nedelja = "nedelja"
    svi_dani = ["ponedeljak", "utorak", "sreda", "cetvrtak", "petak", "subota", "nedelja"]