# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\FilmsScreenDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from database.models.enums import Genres
import datetime


def setupUi( frame):
    
    font = QtGui.QFont()
    font.setPointSize(12)

    frame_layout = QtWidgets.QHBoxLayout()
    frame_layout.setObjectName("frame_layout")
    frame_layout.setContentsMargins(0, 0, 0, 0)


    center_layout = QtWidgets.QVBoxLayout()
    center_layout.setContentsMargins(10, 10, 10, 10)
    center_layout.setObjectName("center_layout")

    header_layout = QtWidgets.QHBoxLayout()
    header_layout.setContentsMargins(0, 0, 0, 0)
    header_layout.setObjectName("header_layout")

    datepicker = QtWidgets.QDateEdit()
    datepicker.setFont(font)
    # datepicker.setStyleSheet("padding: 10px;")
    datepicker.setObjectName("datepicker")
    datepicker.setDate(datetime.datetime.today().date())
    # datepicker.setMinimumDate(datetime.datetime.today().date())
    header_layout.addWidget(datepicker)

    center_layout.addLayout(header_layout)

    table = QtWidgets.QTableWidget()
    table.setEnabled(True)
    table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
    table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
    table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
    table.setCornerButtonEnabled(True)
    table.setAlternatingRowColors(True)
    table.setStyleSheet("background-color: white; color: black")
    table.setObjectName("table")
    table.horizontalHeader().setVisible(True)
    table.horizontalHeader().setCascadingSectionResizes(True)
    table.horizontalHeader().setSortIndicatorShown(False)
    table.horizontalHeader().setStretchLastSection(True)
    table.verticalHeader().setVisible(False)
    table.setColumnCount(7)
    item = QtWidgets.QTableWidgetItem("")
    table.setHorizontalHeaderItem(0, item)
    item = QtWidgets.QTableWidgetItem("Šifra")
    table.setHorizontalHeaderItem(1, item)
    item = QtWidgets.QTableWidgetItem("Film")
    table.setHorizontalHeaderItem(2, item)
    item = QtWidgets.QTableWidgetItem("Sala")
    table.setHorizontalHeaderItem(3, item)
    item = QtWidgets.QTableWidgetItem("Datum")
    table.setHorizontalHeaderItem(4, item)
    item = QtWidgets.QTableWidgetItem("Vreme početka")
    table.setHorizontalHeaderItem(5, item)
    item = QtWidgets.QTableWidgetItem("Vreme kraja")
    table.setHorizontalHeaderItem(6, item)
    table.setColumnWidth(2, 450)

    center_layout.addWidget(table)

    back_button = QtWidgets.QPushButton()
    back_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    back_button.setFocusPolicy(QtCore.Qt.ClickFocus)
    back_button.setText("Nazad")
    back_button.setFont(font)
    back_button.setMaximumWidth(300)
    back_button.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"outline: none;\n"
"padding: 10px 30px;")
    back_button.setAutoDefault(False)
    back_button.setDefault(False)
    back_button.setFlat(True)
    back_button.setObjectName("back_button")
    
    center_layout.addWidget(back_button)

    

    frame_layout.addLayout(center_layout)
    frame.setLayout(frame_layout)

    return {
        "table": table,
        "datepicker": datepicker,
        "back_button": back_button,
    }