# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\FilmsScreenDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


def setupUi( frame):
    
    font = QtGui.QFont()
    font.setPointSize(12)

    main_layout = QtWidgets.QVBoxLayout()
    main_layout.setObjectName("main_layout")

    header_layout = QtWidgets.QHBoxLayout()
    header_layout.setContentsMargins(0, 0, 0, 0)
    header_layout.setObjectName("header_layout")

    name_input = QtWidgets.QLineEdit()
    name_input.setPlaceholderText("Unesi naziv filma...")
    name_input.setFont(font)
    name_input.setStyleSheet("padding: 10px;")
    name_input.setObjectName("name_input")
    header_layout.addWidget(name_input)

    search_button = QtWidgets.QPushButton()
    search_button.setFont(font)
    search_button.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"outline: none;\n"
"padding: 10px 30px;")
    search_button.setObjectName("search_button")
    search_button.setText("Pretraži")
    header_layout.addWidget(search_button)

    filters_button = QtWidgets.QPushButton()
    filters_button.setFont(font)
    filters_button.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"outline: none;\n"
"padding: 10px 30px;")
    filters_button.setObjectName("filters_button")
    filters_button.setText("Filteri")
    header_layout.addWidget(filters_button)
    main_layout.addLayout(header_layout)

    table = QtWidgets.QTableWidget()
    table.setEnabled(True)
    table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
    table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
    table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
    table.setCornerButtonEnabled(True)
    table.setAlternatingRowColors(True)
    table.setStyleSheet("background-color: white; color: black")
    table.setObjectName("table")
    table.horizontalHeader().setVisible(True)
    table.horizontalHeader().setCascadingSectionResizes(True)
    table.horizontalHeader().setSortIndicatorShown(False)
    table.horizontalHeader().setStretchLastSection(True)
    table.verticalHeader().setVisible(False)
    table.setColumnCount(8)
    item = QtWidgets.QTableWidgetItem("Šifra")
    table.setHorizontalHeaderItem(0, item)
    item = QtWidgets.QTableWidgetItem("Naziv")
    table.setHorizontalHeaderItem(1, item)
    item = QtWidgets.QTableWidgetItem("Žanrovi")
    table.setHorizontalHeaderItem(2, item)
    item = QtWidgets.QTableWidgetItem("Trajanje")
    table.setHorizontalHeaderItem(3, item)
    item = QtWidgets.QTableWidgetItem("Režiser")
    table.setHorizontalHeaderItem(4, item)
    item = QtWidgets.QTableWidgetItem("Glavne uloge")
    table.setHorizontalHeaderItem(5, item)
    item = QtWidgets.QTableWidgetItem("Zemlja")
    table.setHorizontalHeaderItem(6, item)
    item = QtWidgets.QTableWidgetItem("Godina")
    table.setHorizontalHeaderItem(7, item)
    table.setColumnWidth(1, 350)
    table.setColumnWidth(2, 400)
    table.setColumnWidth(5, 450)

    main_layout.addWidget(table)

    back_button = QtWidgets.QPushButton()
    back_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    back_button.setFocusPolicy(QtCore.Qt.ClickFocus)
    back_button.setText("Nazad")
    back_button.setFont(font)
    back_button.setMaximumWidth(300)
    back_button.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"outline: none;\n"
"padding: 10px 30px;")
    back_button.setAutoDefault(False)
    back_button.setDefault(False)
    back_button.setFlat(True)
    back_button.setObjectName("back_button")
    
    main_layout.addWidget(back_button)

    frame.setLayout(main_layout)

    return {
        "table": table,
        "name_input": name_input,
        "search_button": search_button,
        "filters_button": filters_button,
        "back_button": back_button
    }