# autor: Imenko Prezimić INDEX ra1234-2016
# fajlovi: zad.S

# Ako vaše rešenje sadrži dodatne fajlove, stavite njihove nazive u liniju fajlovi
# Na primer, ako imate i potprogram u pp.S, iza fajlovi treba da stoji: zad.S pp.S

punos: 		.ascii "Unesite string: \0"
pgreska: 	.ascii "Doslo je do greske u izvrsavanju programa!\n\0"
psuma: 		.ascii "Suma elemenata niza je: \0"
pbroj_oktalnih: .ascii "\nBroj oktalnih elemenata u nizu: \0"
pbroj_decimalnih: .ascii "\nBroj decimalnih elemenata u nizu: \0"
pnovi_red: 	.ascii "\n\0"
