# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\FilmsScreenDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from database.models.enums import Genres
import datetime


def setupUi( frame):
    
    font = QtGui.QFont()
    font.setPointSize(12)

    frame_layout = QtWidgets.QHBoxLayout()
    frame_layout.setObjectName("frame_layout")
    frame_layout.setContentsMargins(0, 0, 0, 0)


    center_layout = QtWidgets.QVBoxLayout()
    center_layout.setContentsMargins(10, 10, 10, 10)
    center_layout.setObjectName("center_layout")

    header_layout = QtWidgets.QHBoxLayout()
    header_layout.setContentsMargins(0, 0, 0, 0)
    header_layout.setObjectName("header_layout")
    header_layout.addStretch()

    filters_button = QtWidgets.QPushButton()
    filters_button.setFont(font)
    filters_button.setMaximumWidth(250)
    filters_button.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"outline: none;\n"
"padding: 10px 30px;")
    filters_button.setObjectName("filters_button")
    filters_button.setText("Filteri")
    filters_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    filters_button.setFixedWidth(300)
    header_layout.addWidget(filters_button)

    center_layout.addLayout(header_layout)

    table = QtWidgets.QTableWidget()
    table.setEnabled(True)
    table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
    table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
    table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
    table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
    table.setCornerButtonEnabled(True)
    table.setAlternatingRowColors(True)
    table.setStyleSheet("background-color: white; color: black")
    table.setObjectName("table")
    table.horizontalHeader().setVisible(True)
    table.horizontalHeader().setCascadingSectionResizes(True)
    table.horizontalHeader().setSortIndicatorShown(False)
    table.horizontalHeader().setStretchLastSection(True)
    table.verticalHeader().setVisible(False)
    table.setColumnCount(12)
    item = QtWidgets.QTableWidgetItem("")
    table.setHorizontalHeaderItem(0, item)
    item = QtWidgets.QTableWidgetItem("")
    table.setHorizontalHeaderItem(1, item)
    item = QtWidgets.QTableWidgetItem("")
    table.setHorizontalHeaderItem(2, item)
    item = QtWidgets.QTableWidgetItem("Šifra")
    table.setHorizontalHeaderItem(3, item)
    item = QtWidgets.QTableWidgetItem("Film")
    table.setHorizontalHeaderItem(4, item)
    item = QtWidgets.QTableWidgetItem("Sala")
    table.setHorizontalHeaderItem(5, item)
    item = QtWidgets.QTableWidgetItem("Status")
    table.setHorizontalHeaderItem(6, item)
    item = QtWidgets.QTableWidgetItem("Datum")
    table.setHorizontalHeaderItem(7, item)
    item = QtWidgets.QTableWidgetItem("Vreme početka")
    table.setHorizontalHeaderItem(8, item)
    item = QtWidgets.QTableWidgetItem("Vreme kraja")
    table.setHorizontalHeaderItem(9, item)
    item = QtWidgets.QTableWidgetItem("Sedište")
    table.setHorizontalHeaderItem(10, item)
    item = QtWidgets.QTableWidgetItem("Ime i prezime")
    table.setHorizontalHeaderItem(11, item)
    table.setColumnWidth(4, 450)

    center_layout.addWidget(table)

    back_button = QtWidgets.QPushButton()
    back_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
    back_button.setFocusPolicy(QtCore.Qt.ClickFocus)
    back_button.setText("Nazad")
    back_button.setFont(font)
    back_button.setMaximumWidth(300)
    back_button.setStyleSheet("background: white;\n"
"color: black;\n"
"border: 1px solid black;\n"
"border-radius: 5px;\n"
"outline: none;\n"
"padding: 10px 30px;")
    back_button.setAutoDefault(False)
    back_button.setDefault(False)
    back_button.setFlat(True)
    back_button.setObjectName("back_button")
    
    center_layout.addWidget(back_button)

    filters_scroll_area = QtWidgets.QScrollArea()

    filters_scroll_area.setWidgetResizable(True)
    filters_scroll_area.setObjectName("scrollArea")
    filters_scroll_area.setMinimumWidth(350)
    filters_scroll_area_layout = QtWidgets.QVBoxLayout()
    filters_scroll_area.setLayout(filters_scroll_area_layout)

    filters_content_widget = QtWidgets.QWidget()
    filters_content_widget.setObjectName("content")
    # filters_content_widget.setMinimumWidth(300)
    filters_scroll_area.setWidget(filters_content_widget)

    filters_content_layout = QtWidgets.QVBoxLayout()
    filters_content_layout.setObjectName("filters_content_layout")

    filters_content_widget.setLayout(filters_content_layout)

    projections_group = QtWidgets.QGroupBox(frame)
    projections_group.setTitle("Projekcije")
    projections_group.setObjectName("projections_group")
    projections_group.setFont(font)
    projections_group.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum))

    projections_layout = QtWidgets.QVBoxLayout(projections_group)
    projections_layout.setObjectName("projections_layout")

    def add_projection(text):
        projection = QtWidgets.QCheckBox(projections_group)
        projection.setText(text)
        projection.setFont(font)
        projection.setStyleSheet("color: white")
        projections_layout.addWidget(projection)
        return projection
    
    def clear_projections():
        for i in reversed(range(projections_layout.count())): 
            projections_layout.itemAt(i).widget().setParent(None)
    
    filters_content_layout.addWidget(projections_group)

    films_group = QtWidgets.QGroupBox(frame)
    films_group.setTitle("Filmovi")
    films_group.setObjectName("films_group")
    films_group.setFont(font)
    films_group.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum))

    films_layout = QtWidgets.QVBoxLayout(films_group)
    films_layout.setObjectName("films_layout")

    def add_film(text):
        film = QtWidgets.QCheckBox(films_group)
        film.setText(text)
        film.setFont(font)
        film.setStyleSheet("color: white")
        films_layout.addWidget(film)
        return film
    
    def clear_films():
        for i in reversed(range(films_layout.count())): 
            films_layout.itemAt(i).widget().setParent(None)
    
    filters_content_layout.addWidget(films_group)

    status_group = QtWidgets.QGroupBox(frame)
    status_group.setTitle("Status")
    status_group.setObjectName("status_group")
    status_group.setFont(font)
    status_group.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum))

    status_layout = QtWidgets.QVBoxLayout(status_group)
    status_layout.setObjectName("status_layout")

    def add_status(text):
        film = QtWidgets.QCheckBox(status_group)
        film.setText(text)
        film.setFont(font)
        film.setStyleSheet("color: white")
        status_layout.addWidget(film)
        return film
    
    def clear_status():
        for i in reversed(range(status_layout.count())): 
            status_layout.itemAt(i).widget().setParent(None)
    
    filters_content_layout.addWidget(status_group)


    name_group = QtWidgets.QGroupBox(frame)
    name_group.setTitle("Ime i prezime")
    name_group.setObjectName("name_group")
    name_group.setFont(font)
    name_group.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum))

    name_layout = QtWidgets.QVBoxLayout(name_group)
    name_layout.setObjectName("name_layout")

    name_input = QtWidgets.QLineEdit(name_group)
    name_input.setStyleSheet("padding: 5px 10px;")
    name_input.setDragEnabled(False)
    name_input.setObjectName("name_input")
    name_input.setFont(font)
    
    name_layout.addWidget(name_input)

    filters_content_layout.addWidget(name_group)

    date_group = QtWidgets.QGroupBox(frame)
    date_group.setTitle("Datum")
    date_group.setObjectName("date_group")
    date_group.setFont(font)
    date_group.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum))

    min_date_label = QtWidgets.QLabel(frame)
    min_date_label.setText("Od:")
    min_date_label.setFont(font)
    min_date_label.setStyleSheet("color: white")
    min_date_label.setObjectName("min_date_label")

    min_date_de = QtWidgets.QDateEdit(frame)
    min_date_de.setFont(font)
    min_date_de.setStyleSheet("padding: 5px 10px; color: white; border: 1px solid white;")    
    min_date_de.setObjectName("min_date_de")

    max_date_label = QtWidgets.QLabel(frame)
    max_date_label.setText("Do:")
    max_date_label.setFont(font)
    max_date_label.setStyleSheet("color: white")
    max_date_label.setObjectName("max_date_label")

    max_date_de = QtWidgets.QDateEdit(frame)
    max_date_de.setFont(font)
    max_date_de.setStyleSheet("padding: 5px 10px; color: white; border: 1px solid white;")    
    max_date_de.setObjectName("max_date_de")

    date_layout = QtWidgets.QVBoxLayout()
    date_layout.addWidget(min_date_label)
    date_layout.addWidget(min_date_de)
    date_layout.addWidget(max_date_label)
    date_layout.addWidget(max_date_de)

    date_group.setLayout(date_layout)
    filters_content_layout.addWidget(date_group)

    time_group = QtWidgets.QGroupBox(frame)
    time_group.setTitle("Vreme")
    time_group.setObjectName("time_group")
    time_group.setFont(font)
    time_group.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum))

    min_time_label = QtWidgets.QLabel(frame)
    min_time_label.setText("Od:")
    min_time_label.setFont(font)
    min_time_label.setStyleSheet("color: white")
    min_time_label.setObjectName("min_time_label")

    min_time_te = QtWidgets.QTimeEdit(frame)
    min_time_te.setFont(font)
    min_time_te.setStyleSheet("padding: 5px 10px; color: white; border: 1px solid white;")    
    min_time_te.setObjectName("min_time_te")

    max_time_label = QtWidgets.QLabel(frame)
    max_time_label.setText("Do:")
    max_time_label.setFont(font)
    max_time_label.setStyleSheet("color: white")
    max_time_label.setObjectName("max_time_label")

    max_time_te = QtWidgets.QTimeEdit(frame)
    max_time_te.setFont(font)
    max_time_te.setStyleSheet("padding: 5px 10px; color: white; border: 1px solid white;")    
    max_time_te.setObjectName("max_time_te")

    time_layout = QtWidgets.QVBoxLayout()
    time_layout.addWidget(min_time_label)
    time_layout.addWidget(min_time_te)
    time_layout.addWidget(max_time_label)
    time_layout.addWidget(max_time_te)

    time_group.setLayout(time_layout)
    filters_content_layout.addWidget(time_group)

    filters_content_layout.addStretch()
    
    frame_layout.addLayout(center_layout)
    frame_layout.addWidget(filters_scroll_area)
    frame.setLayout(frame_layout)

    return {
        "table": table,
        "back_button": back_button,
        "filters_button": filters_button,
        "min_time_te": min_time_te,
        "max_time_te": max_time_te,
        "min_date_de": min_date_de,
        "max_date_de": max_date_de,
        "filters_scroll_area": filters_scroll_area,
        "name_input": name_input
    }, {
        "add_status": add_status,
        "clear_status": clear_status,
        "add_film": add_film,
        "clear_films": clear_films,
        "add_projection": add_projection,
        "clear_projections": clear_projections,
        # "add_hall": add_hall,
        # "clear_halls": clear_halls
    }